### PR TITLE
Add short -N alias for --no-reuse-existing-virtualenvs

### LINKED ISSUE #624: Add a single character shortcut for --no-reuse-existing-virtualenvs
### How would this feature be useful?

A common way to use Nox that saves a lot of time when re-running sessions over and over by avoiding recreating venvs is to set:

```py
nox.options.reuse_existing_virtualenvs = True
```

You can see the `pip` developers use this:

- https://github.com/pypa/pip/blob/main/noxfile.py#L19

When dependencies _do_ change, the developer can then run:

```
nox --no-reuse-existing-virtualenvs -s test
```

Given this can be a very common work flow, avoiding having to type out `--no-reuse-existing-virtualenvs` on the command line would be a great improvement to UX.

### A note on `tox`

What I'm describing above is also the default workflow for `tox` users. Many people moving from `tox` will be familiar with this workflow. (e.g. `tox` re-uses venvs by default, and `tox -r` is an opt-in recreation).

### Describe the solution you'd like

Add a new alias for `--no-reuse-existing-virtualenvs`, for example `-C` for "Create"

```
nox -C -s test
```

### PR DESCRIPTION
**Pull request by johnthagen**
Closes #624

### CODE REVIEW

**Comment by johnthagen** [comment]
```
$ python nox --help
...
  -nr, --no-reuse-existing-virtualenvs
                        Disables --reuse-existing-virtualenvs if it is enabled in the Noxfile.
```

**Comment by johnthagen** [comment]
@DiddiLeija @crwilcox @ktbarrett Could you review?

Specifically, are we sure we want to set a precedent of using a multi-letter short option (`-nr`) vs picking another single letter short option (such as `-C`)?

**Comment by ktbarrett** [comment]
Looks fine to me, but I'm no maintainer. 

>are we sure we want to set a precedent of using a multi-letter short option

The precedent is already set by a number of other options. Scrolling up a few lines shows `-fb`, `-db`, and a couple others.

**Comment by johnthagen** [comment]
> The precedent is already set by a number of other options. Scrolling up a few lines shows `-fb`, `-db`, and a couple others.

That is a good point and something I missed.

**Comment by FollowTheProcess** [comment]
Is `-N` available? That might be better than `-nr`?

**Comment by johnthagen** [comment]
It appears that `-N` is available. I'm happy to change to that if that is the consensus of the Nox team.

**Comment by DiddiLeija** [comment]
No objections from me :)

**Comment by FollowTheProcess** [comment]
> It appears that -N is available. I'm happy to change to that if that is the consensus of the Nox team.

I'm easy either way really it's not a dealbreaker. I just don't like the look of "short" options with more than 1 character (I know we already have some) We have a precedent for capitals with `-R` for reuse and no install (from memory) so `-N` would fit better IMO

**Comment by johnthagen** [comment]
Sounds good. I've changed to `-N`. I also prefer this way.

When merging, if someone could hit the "Squash" button in the GitHub UI, I'd appreciate it.

**Comment by FollowTheProcess** [comment]
> When merging, if someone could hit the "Squash" button in the GitHub UI, I'd appreciate it.

We only allow squashes anyway 👍🏻

**Review by FollowTheProcess — APPROVED** [review]
LGTM, nice job thanks!

**Pull request merged**
