### PR TITLE
Point action docs to 2022.8.7 not latest

### PR DESCRIPTION
**Pull request by FollowTheProcess**
Fixes a mention in the docs to `@latest` which doesn't actually refer to a valid tag, my bad for not spotting! 👍🏻 Thanks @henryiii

### CODE REVIEW

**Review by DiddiLeija — APPROVED** [review]
Thank you both @FollowTheProcess and @henryiii!

Small question: Is `@main` possible, instead of `@latest`? If not, I'm ok with merging this :+1:

**Comment by DiddiLeija** [comment]
> Small question: Is `@main` possible, instead of `@latest`? If not, I'm ok with merging this 👍

Ahh sorry, I didn't read #662 yet :/

**Comment by henryiii** [comment]
`@main` is fine too, you can put any branch or tag name there.

**Comment by DiddiLeija** [comment]
Ok. I'm personally more comfortable with `@main`, but a tag is fine too (however, we'll have to update that tag frequently).

**Comment by FollowTheProcess** [comment]
A specific tag is always preferable IMO, it means a user of the action is always getting an exact version rather than whatever is on the main branch (which may, although unlikely, break). What do we think?

**Comment by DiddiLeija** [comment]
> If we need to keep it up to date with new versions there's things like bump2version that can find and replace, or we just leave it with a comment that says e.g "any tagged version will work here"

That would resolve my concerns of using a specific tag!

**Pull request merged**
