### PR TITLE
chore: use dependency-groups

### PR DESCRIPTION
**Pull request by henryiii**
As a side affect of using dependency-groups, `uv run pytest` works out of the box! I've split the test requirements into test and dev.

Also, the old dev requirements was including the conda-test file, which is actually a list of conda packages, not a PyPI list.

I've also modernized a few other things, like using `default=`, the python versions are read from the classifiers, author list fixed, and pypy3.9 is no longer supported by upstream.

### CODE REVIEW

**Comment by henryiii** [comment]
@theacodes, @dhermes, @cjolowicz, or @DiddiLeija, could one of you enable PR builds on readthedocs? I've modernized the readthedocs config, should be much faster, but I'd like to see if it builds correctly in the PR.

**Comment by theacodes** [comment]
@henryiii done!

**Comment by henryiii** [comment]
There still seems to be something missing, like a webhook. Could you re-sync the webhook, perhaps?

https://docs.readthedocs.io/en/stable/guides/pull-requests.html

**Comment by theacodes** [comment]
Alright, I resynced the webhook. Give it another shot?

**Comment by henryiii** [comment]
That got it, thanks!

**Comment by henryiii** [comment]
Cuts the docs time to less than half of that it was before. :)

**Pull request merged**
