### PR TITLE
Release 2024.03.02

### PR DESCRIPTION
**Pull request by cjolowicz**
The changelog is essentially generated by GitHub Release, which I've quickly classified by type. If anybody wants to improve the descriptions (they'd benefit), please go ahead 😉

### CODE REVIEW

**Comment by cjolowicz** [comment]
Cleaning up the release notes a little before pressing the button...

**Comment by cjolowicz** [comment]
The ci.yml workflow doesn't trigger on tags 🤔  so this release isn't on PyPI yet.

@theacodes @crwilcox could you publish the package?

**Comment by theacodes** [comment]
Manual release is intentional. I'll release tomorrow.

**Comment by theacodes** [comment]
It's published! https://pypi.org/project/nox/2024.3.2/#description

**Pull request merged**
