### PR TITLE
ci: fix coverage combine for different OS's

### PR DESCRIPTION
**Pull request by henryiii**
Different OS's are producing the same files currently. Noticed in #762. I think this might be why #772 is failing, too.

### CODE REVIEW

**Comment by cjolowicz** [comment]
Would something like this help with merging the Windows paths?

```toml
[tool.coverage.paths]
source = ["nox", "*/site-packages"]

[tool.coverage.run]
source = ["nox"]
```

**Comment by henryiii** [comment]
I can try it. Have no idea why the `D:\a\nox\nox\__init__.py` is not being reported as a relative path.

**Comment by henryiii** [comment]
I'll try that, as the first one didn't work. I also might upload the .coverage files.

**Comment by henryiii** [comment]
When it works, it shows `Matched path 'D:\\a\\nox\\nox\\nox\\workflow.py' to rule '*/nox' -> 'nox/', producing 'nox/workflow.py'`. Not sure what a failing run looks like.

**Comment by henryiii** [comment]
FYI, this is what the coverage looks like:

```
sqlite> SELECT * FROM file;
1|D:\a\nox\nox\nox\__init__.py
2|D:\a\nox\nox\nox\_options.py
3|D:\a\nox\nox\nox\_option_set.py
4|D:\a\nox\nox\nox\tasks.py
5|D:\a\nox\nox\nox\registry.py
6|D:\a\nox\nox\nox\_decorators.py
7|D:\a\nox\nox\nox\_typing.py
8|D:\a\nox\nox\nox\_version.py
9|D:\a\nox\nox\nox\logger.py
10|D:\a\nox\nox\nox\manifest.py
11|D:\a\nox\nox\nox\sessions.py
12|D:\a\nox\nox\nox\command.py
13|D:\a\nox\nox\nox\popen.py
14|D:\a\nox\nox\nox\virtualenv.py
15|D:\a\nox\nox\nox\_parametrize.py
16|D:\a\nox\nox\nox\tox_to_nox.py
17|D:\a\nox\nox\nox\workflow.py
18|D:\a\nox\nox\nox\__main__.py
19|nox\__init__.py
20|nox\_options.py
21|nox\_option_set.py
22|nox\tasks.py
23|nox\registry.py
24|nox\_decorators.py
25|nox\_version.py
26|nox\logger.py
27|nox\manifest.py
28|nox\sessions.py
29|nox\command.py
30|nox\popen.py
31|nox\virtualenv.py
32|nox\_parametrize.py
33|nox\__main__.py
34|nox\workflow.py
35|nox\tox_to_nox.py
36|nox\_typing.py
```

This is true for both passing and failing tests AFAICT.

**Review by cjolowicz — APPROVED** [review]

**Pull request merged**
