### PR TITLE
docs: update some links

### PR DESCRIPTION
**Pull request by henryiii**
This adds some links, updates a few more projects, and adds me too. Also updates the install suggestion based on the README suggestion.

### CODE REVIEW

**Review by DiddiLeija — APPROVED** [review]
I'd say this looks great, thanks @henryiii!

**Comment by henryiii** [comment]
(Ignore the FP revert, pushed a CI fix to this branch by mistake!)

**Comment by DiddiLeija** [comment]
Whoops, seems like coverage is unhappy with the merge :man_facepalming:

**Comment by henryiii** [comment]
That’s a random failure. Hopefully the coverage fix PRs will help.

**Comment by henryiii** [comment]
Hmm, there was a patch release of coverage yesterday, about the time this started failing. Hard to tell for sure, but very suspicious.

**Pull request merged**
