### PR TITLE
Add invite link to the discord server to CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by dcermak**

### CODE REVIEW

**Comment by FollowTheProcess** [comment]
Any issues with the invite link being public? Not overly familiar with discord so don't know if this is the done thing or not

**Comment by dcermak** [comment]
Many projects that I have seen using discord put a join link into their readme or somewhere else in a prominent place, so I guess there shouldn't be huge ramifications. Of course this will make it easier for people to join, so the server could become more crowded and require more moderation from the server admin.

**Comment by DiddiLeija** [comment]
> Of course this will make it easier for people to join, so the server could become more crowded and require more moderation from the server admin.

The Winterbloom server is a nicely moderated server, it has their rules, and the community is big (even without a lot of Nox-interested people). So I don't think there's a problem at all :)

**Comment by theacodes** [comment]
Absolutely fine for the discord invite to be public.

**Review by DiddiLeija — APPROVED** [review]

**Comment by FollowTheProcess** [comment]
Thanks @dcermak 🎉

**Pull request merged**
