### PR TITLE
Add docs for #180

### PR DESCRIPTION
**Pull request by hynek**
I found this extremely useful feature only by accident and Googling!

Not sure if y'all enjoy retroactive changelog editing…

### CODE REVIEW

**Comment by theacodes** [comment]
@hynek thanks for sending this!

There's actually an even easier way to accomplish the example shown:

```python
commit = session.run("git", "rev-parse", "--short", "HEAD", external=True, silent=True)
```

**Comment by hynek** [comment]
aaargh now i understand [Henry's comment](https://github.com/wntrblm/nox/issues/218#issuecomment-1005178204). I never read the full help string b/c i didn't want silence.

I guess i'll just rewrite example (but leave the new API docs)? 😅

**Comment by theacodes** [comment]
Yeah that would be awesome. It's still a useful thing to document, I'd just
want it to have a more practical example.

**Comment by DiddiLeija** [comment]
Yeah, it's worthy to document this. The CI failed, so I decided to re-run the failed checks.

**Comment by hynek** [comment]
I've rewritten the example and clarified the arguments of stdout/stderr. I don't think they need their own examples; with silent=True they're rather fringe options.

**Review by theacodes — APPROVED** [review]

**Comment by theacodes** [comment]
Thank you so much, @hynek!

**Pull request merged**
