### PR TITLE
chore: minor touchups

### PR DESCRIPTION
**Pull request by henryiii**
Several minor touchups too small on their own.

- chore: remove wheel
- chore: include flake8-bugbear's extra checks
- chore: fix pycln's arg in pre-commit

### CODE REVIEW

**Comment by FollowTheProcess** [comment]
Looks good @henryiii thanks! On a bit of a roll at the moment! Just for my own curiosity (and laziness to find out by myself 😄) why do we not need wheel anymore?

**Comment by henryiii** [comment]
Also see https://github.com/pypa/packaging.python.org/pull/1050

**Comment by henryiii** [comment]
> On a bit of a roll at the moment!

At least partially inspired by https://scikit-hep.org/developer/reporeview :)

**Comment by FollowTheProcess** [comment]
> At least partially inspired by https://scikit-hep.org/developer/reporeview :)

This is super cool!

**Pull request merged**
